<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CpuZ80.Core\CpuZ80.Core.csproj" />
    <ProjectReference Include="..\Machines.Common\Machines.Common.csproj" />
    <ProjectReference Include="..\Machines.Zx80\Machines.Zx80.csproj" />
    <ProjectReference Include="..\Machines.Sinclair.Common\Machines.Sinclair.Common.csproj" />
  </ItemGroup>

</Project>
