<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>zx80</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adapters.Raylib\Adapters.Raylib.csproj" />
    <ProjectReference Include="..\Machines.Zx80\Machines.Zx80.csproj" />
    <ProjectReference Include="..\Machines.Sinclair.Common\Machines.Sinclair.Common.csproj" />
  </ItemGroup>

</Project>
