// <auto-generated>
// This file is generated by CpuZ80.CodeGen.
// </auto-generated>

namespace CpuZ80.Core;

public sealed partial class Cpu
{
    private void StepGenerated(byte opcode)
    {
        switch (opcode)
        {
            case 0x00: /* NOP */ TotalCycles += 4UL; break;
            default:
                throw new System.NotImplementedException($"Opcode 0x{opcode:X2} not implemented in generator.");
        }
    }
}
