using System.Text;

namespace CpuZ80.CodeGen;

class Program
{
    static void Main(string[] args)
    {
        string outputPath = args.Length > 0 ? args[0] : "../CpuZ80.Core/Cpu.Generated.cs";
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by CpuZ80.CodeGen.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace CpuZ80.Core;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class Cpu");
        sb.AppendLine("{");
        sb.AppendLine("    private void StepGenerated(byte opcode)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (opcode)");
        sb.AppendLine("        {");
        sb.AppendLine("            case 0x00: /* NOP */ TotalCycles += 4UL; break;");

        string[] regs = { "B", "C", "D", "E", "H", "L", "_bus.Read(HL)", "A" };
        for (int i = 0; i < 8; i++)
        {
            int opcode = 0x80 + i;
            string reg = regs[i];
            int cycles = (i == 6) ? 7 : 4;
            sb.AppendLine($"            case 0x{opcode:X2}: /* ADD A, {reg} */ DoAdd({reg}); TotalCycles += {cycles}UL; break;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                throw new System.NotImplementedException($\"Opcode 0x{opcode:X2} not implemented in generator.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        System.IO.File.WriteAllText(outputPath, sb.ToString());
        System.Console.WriteLine($"Generated {outputPath}");
    }
}
