using System.Text;

namespace CpuZ80.CodeGen;

class Program
{
    static void Main(string[] args)
    {
        string outputPath = args.Length > 0 ? args[0] : "../CpuZ80.Core/Cpu.Generated.cs";
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file is generated by CpuZ80.CodeGen.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("namespace CpuZ80.Core;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class Cpu");
        sb.AppendLine("{");
        sb.AppendLine("    private void StepGenerated(byte opcode)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (opcode)");
        sb.AppendLine("        {");
        sb.AppendLine("            case 0x00: /* NOP */ TotalCycles += 4UL; break;");
        sb.AppendLine("            default:");
        sb.AppendLine("                throw new System.NotImplementedException($\"Opcode 0x{opcode:X2} not implemented in generator.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        System.IO.File.WriteAllText(outputPath, sb.ToString());
        System.Console.WriteLine($"Generated {outputPath}");
    }
}
